// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIkFebyI6IvJvEYjlEUxmmsLYThxlEoB8',
    appId: '1:542264660326:web:db06d96dce2ac441f0b8a7',
    messagingSenderId: '542264660326',
    projectId: 'smart-hafazan-13c90',
    authDomain: 'smart-hafazan-13c90.firebaseapp.com',
    storageBucket: 'smart-hafazan-13c90.appspot.com',
    measurementId: 'G-MGTZTRQ1NL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHD09f9T7IcVXemJ1uZ-wG_9pre8mArRM',
    appId: '1:542264660326:android:b04a9743123e6bd8f0b8a7',
    messagingSenderId: '542264660326',
    projectId: 'smart-hafazan-13c90',
    storageBucket: 'smart-hafazan-13c90.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC409T-AeX_k9-DiHO099zaJUgGklZuUs',
    appId: '1:542264660326:ios:ef886b058c620aa1f0b8a7',
    messagingSenderId: '542264660326',
    projectId: 'smart-hafazan-13c90',
    storageBucket: 'smart-hafazan-13c90.appspot.com',
    iosBundleId: 'com.example.smartHafazanNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCC409T-AeX_k9-DiHO099zaJUgGklZuUs',
    appId: '1:542264660326:ios:19de6d0f526dbc25f0b8a7',
    messagingSenderId: '542264660326',
    projectId: 'smart-hafazan-13c90',
    storageBucket: 'smart-hafazan-13c90.appspot.com',
    iosBundleId: 'com.example.smartHafazanNew.RunnerTests',
  );
}
